version: '2'

services:

  vtiger: &vtiger
    build: ./
    environment:
      - VT_DEBUG=true
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "40080:80"
    volumes:
      - ./:/app
      - ./vtiger-cli:/var/www/html/include/vtiger-cli
    links:
      - mysql
      - adminer

  adminer:
    image: javanile/adminer
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "40081:8080"
    links:
      - mysql

  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql:rw
      - ./:/vtiger:rw

  composer:
    <<: *vtiger
    entrypoint: ['composer']

  phpunit:
    <<: *vtiger
    entrypoint: ['./vendor/bin/phpunit']

  box:
    <<: *vtiger
    entrypoint: ['php', '-d', 'phar.readonly=off', './vendor/bin/box']

volumes:
  mysql:
