#!/bin/bash

##
# gitlab-ci-helper.sh
#
# Copyright (c) 2020 Francesco Bianco <bianco@javanile.org>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
##

set -e

echo '        __  _                '
echo ' _   __/ /_(_)___ ____  _____'
echo '| | / / __/ / __ `/ _ \/ ___/'
echo '| |/ / /_/ / /_/ /  __/ /    '
echo '|___/\__/_/\__, /\___/_/  CLI (v0.1.0)'
echo '          /____/             '
echo '                             '

bin=/usr/local/bin/vtiger
url=https://github.com/javanile/vtiger-cli/raw/main/dist/vtiger-cli.phar

root () { [[ ${EUID} -ne 0 ]] && sudo $* || $*; }

echo "Installing console tool to all system users"

root curl -fsSLo "${bin}" "${url}"
root chmod +x "${bin}"

echo "Console tool for vtiger is ready."
