#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require_once __DIR__ . '/vendor/autoload.php';
} elseif (file_exists(__DIR__ . '/../autoload.php')) {
    require_once __DIR__ . '/../autoload.php';
} else {
    require_once __DIR__ . '/../../autoload.php';
}

use Javanile\VtigerCli\App;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\Console\Formatter\OutputFormatterStyle;

$app = new App(getcwd());

$app->command('info', [$app, 'info']);

$out = new ConsoleOutput();
$out->getFormatter()->setStyle('error', new OutputFormatterStyle('black', 'red'));

$app->run(null, $out);

/*
use Javanile\VtigerCli\VtigerCli as App;

use Symfony\Component\Console\Output\OutputInterface;

$app = new App(getcwd());

$app->command('info', function(OutputInterface $io) {

  $io->writeln("asd");
});
$app->command('install', [$app, 'install']);
$app->command('addEntityMethod [Module] [Callable]', [$app, 'addEntityMethod']);
$app->command('apply [Callable]', [$app, 'apply']);

*/