#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require_once __DIR__ . '/vendor/autoload.php';
} elseif (file_exists(__DIR__ . '/../autoload.php')) {
    require_once __DIR__ . '/../autoload.php';
} else {
    require_once __DIR__ . '/../../autoload.php';
}

use Javanile\VtigerCli\VtigerCli as VtigerCliAlias;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\Console\Formatter\OutputFormatterStyle;

$cli = new VtigerCliAlias(getcwd());

$cli->command('info', [$app, 'info']);
$cli->command('install', [$app, 'install']);
$cli->command('addEntityMethod [Module] [Callable]', [$app, 'addEntityMethod']);
$cli->command('apply [Callable]', [$app, 'apply']);

$output = new ConsoleOutput();
$output->getFormatter()->setStyle('error', new OutputFormatterStyle('black', 'red'));

$cli->run(null, $output);
